-- ============================================================================
-- BRIEF, NO-CORTEX PATH. Counts, not prose. Honest about being counts.
-- ============================================================================
USE ROLE SYSADMIN;
USE SCHEMA CONSENT.APP;

TRUNCATE TABLE IMPACT_BRIEF;
INSERT INTO IMPACT_BRIEF (generated_at, method, brief)
SELECT CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
       'regex',
       'Across ' || COUNT(*) || ' cases logged between '
       || MIN(intake_date) || ' and ' || MAX(intake_date) || ', '
       || COUNT_IF(unresolved) || ' remain unresolved. '
       || 'The largest category is '
       || MAX(need_type) || '. Generated by aggregation, not by a model.'
FROM SAFE_CASES;

GRANT SELECT ON TABLE CONSENT.APP.IMPACT_BRIEF TO ROLE CONSENT_APP;
SELECT brief FROM IMPACT_BRIEF;
